name: 'adventure_works'
version: '1.0.0'
config-version: 2

profile: 'adventure_works'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  adventure_works:
    +materialized: ephemeral
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
